############################################
# Windows Server Core (1809) with IIS
# DockerFile Version: 1.0
############################################

# Base Image
FROM mcr.microsoft.com/powershell:6.1.3-windowsservercore-1809

# Maintainer
LABEL Author="Francesco Sodano" \
    Version=1.0

# Environment Variables
ENV chocolateyUseWindowsCompression false

# Image Preparation
USER ContainerAdministrator

# Adding Features
RUN powershell.exe -NoProfile
RUN powershell.exe -NoProfile -Command Install-WindowsFeature Web-Server -Confirm:$false; \
    Install-WindowsFeature Web-App-Dev; \
    Install-WindowsFeature Web-Asp-Net45; \
    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress; \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe" -OutFile "C:\ServiceMonitor.exe";

# Installing Git
RUN powershell.exe -NoProfile -Command choco install -fy git --param "/NoGitLfs /SChannel /NoAutoCrlf"

# Adding Content for Git
RUN powershell.exe -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*; \
    powershell.exe -NoProfile -Command git.exe clone https://github.com/reruns/mario.git C:\inetpub\wwwroot
WORKDIR /inetpub/wwwroot

# Expose Ports and EntryPoint
EXPOSE 80
ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]


